### ISSUE TITLE
求与时俱进，laravel 都5.7拉。。。

### ISSUE THREAD

**Issue by icedfish** [wutongwan/laravel-lego#168]
![image](https://user-images.githubusercontent.com/1222861/48419163-3843a980-e792-11e8-832b-74959296c81b.png)

**Comment by icedfish** [comment]
@zhwei 和laravel新版有啥已知不兼容么？ 否则我就只是改下配置文件去了。

**Comment by zhwei** [comment]
@icedfish 没有已知不兼容项，明天我升级 demo 测一下

**Comment by zhwei** [comment]
可以先用这个 beta https://github.com/wutongwan/laravel-lego/releases/tag/0.3.15-beta

**Comment by zhwei** [comment]
https://github.com/wutongwan/laravel-lego/releases/tag/0.3.15

**Comment by icedfish** [comment]
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

**Comment by zhwei** [comment]
可以，现在也在逐步替换成模板了
