### ISSUE TITLE
Lego定期体检

### ISSUE THREAD

**Issue by icedfish** [wutongwan/laravel-lego#82]
从头体验了一次Lego的安装和初始化，提一些意见：

- [x] travis-ci build error 
- [x] php artisan lego:generate-ide-helper的方式不友好，改为build的时候自动添加注释会更方便使用。
- [x] datagrid变成移动端自适应？
- [ ] release以后没有自动提交到packagist

**Comment by icedfish** [comment]
packagist的webhook没生效很奇怪，刚手动去packagist点了一次update才对的。

我更新了一次token，@zhwei 最近再打个新release试一下吧。

**Comment by zhwei** [comment]
OK，我晚点试试

**Comment by zhwei** [comment]
外部调用 generate ide helper 的一个好处是：可以为 Lego 外部定义的 Field 生成自动补全代码，不过这个和原有的不冲突，lego 内部可以先带一份内置的 Field 自动补全

**Comment by zhwei** [comment]
packagist 现在好像就是实时更新的，但是 Settings  => Services 仍然显示 token never triggered

**Comment by icedfish** [comment]
恩，service一直不成功。 要不改为直接打release包的时候，手动到packagist触发一下吧。
